# Generated by Django 4.1.3 on 2022-11-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_year', models.BooleanField(default=False)),
                ('Second_year', models.BooleanField(default=False)),
                ('Third_year', models.BooleanField(default=False)),
                ('Fourth_year', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.colleges')),
            ],
        ),
    ]
