# Generated by Django 4.1.3 on 2022-11-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_technicaltraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaltraining',
            name='Rates',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='technicaltraining',
            name='dates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
