# Generated by Django 4.1.3 on 2022-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_technicaltraining_rates_technicaltraining_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicaltraining',
            name='dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
